In [2]:
%%html
<script src="https://kit.fontawesome.com/751ade44c1.js" crossorigin="anonymous"></script>

<style>
:root {
    --red: #d9534f;
    --yellow: #f0ad4e;
    --green: #5cb85c;
    --blue: #0275d8;
    --light-blue: #5bc0de;
    --dark-blue: #073b4c;
    --purple: #6A4C93;
}
    
.important {
    color: var(--yellow);
}

.optional {
    color: var(--green);
}
</style>


# <i class="fas fa-circle exercise"></i>Linear Algebra using Python and Numpy
<span class="badge badge-pill important-bg">exercise</span> <span class="badge badge-pill badge-dark">notebook</span>


This exercise introduces basic linear algebra operations in Numpy as well as how to use it to solve systems of linear equations. Your goal should be to familiarise yourself with the theoretical linear algebra concepts and learn some standard applications in Numpy. We cover the following topics :

* Basic matrix operations (elementwise operations, transpose, multiplication, inverse)
* Properties of matrix multiplication and inversion
* Linear equations in matrix form
* Solving linear equations using matrix inverses


## Matrix operations and algebra
In this exercise you will perform basic linear algebra operations using Numpy.


In [1]:
import numpy as np
import matplotlib.pyplot as plt


In [6]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])



### Task A):
1. Calculate $A-B$. Then convert each of $A$, $B$, to `np.float16` (use `np.float16(a)`) and try again. Do you observe any differences?


In [9]:
print(A-B)
print(np.float16(A-B))

[[ 17.         -14.5         14.33333333 -12.75      ]
 [ 12.5        -10.66666667  10.25        -8.8       ]
 [  8.33333333  -6.75         6.2         -4.83333333]
 [  4.25        -2.8          2.16666667  -0.85714286]]
[[ 17.    -14.5    14.336 -12.75 ]
 [ 12.5   -10.664  10.25   -8.8  ]
 [  8.336  -6.75    6.2    -4.832]
 [  4.25   -2.8     2.166  -0.857]]


2. Show that $AC \not= CA$. Use the function `np.dot()`. 


In [12]:
print(np.dot(A, C))
print(np.dot(C, A))

[[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
[[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]


3. Use the `*` operator to calculate `A*C`. Explain the difference between the operators `np.dot` and `*`.


In [14]:
print(A*C)
print(np.dot(A, C))

# * multiplies each value in one matrix with the corresponding positioned value in the other matrix
# np.dot calculates the dot product, which is not the same

[[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]
[[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]


4. Use `np.linalg.inv` to calculate  the inverse of $A$ and $C$. ([np.linalg.inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html))


In [17]:
print(np.linalg.inv(A))
print(np.linalg.inv(C))

[[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
[[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]


5. Calculate $AA^{-1}$ and $CC^{-1}$. Explain the results.  *Note: You may want to use `np.around(a, dec)` ([np.around(a, dec)](https://docs.scipy.org/doc/numpy/reference/generated/numpy.around.html#numpy.around)) to round the results for easy visual inspection*.


In [23]:
invA = np.linalg.inv(A)
invC = np.linalg.inv(C)

print(np.around(np.dot(A, invA)))
print(np.around(np.dot(C, invC)))

[[ 1.  0.  0.  0.]
 [-0.  1. -0.  0.]
 [ 0.  0.  1. -0.]
 [ 0.  0.  0.  1.]]
[[ 1.  0.  0.  0.]
 [-0.  1.  0.  0.]
 [-0.  0.  1.  0.]
 [-0.  0. -0.  1.]]


### Task B)
Define two matrices $D$ and $E$ and  their inverses:


In [24]:
D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)


1-a. Show that $D^{-1}E^{-1}$ equals to $(ED)^{-1}$.

1-b. Show that $D^{-1}E^{-1}$ is not equal  to $(DE)^{-1}$.


In [27]:
print(np.dot(D_inv, E_inv))
print(np.linalg.inv(np.dot(E, D)))

[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]


2-a. Show why $(D^{-1})^T=(D^T)^{-1}$ as was proved in the pen and paper exercise. 

The transpose of an array $D$ in Numpy can be calculated with `D.T`.


In [32]:
print(D_inv.T)
print(np.linalg.inv(D.T))


[[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429  0.        ]
 [-0.33862434 -0.2010582   0.59259259]]
[[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429 -0.        ]
 [-0.33862434 -0.2010582   0.59259259]]
[ 1. -1.]


## Linear equations


 Matrices can represent systems of linear equations 

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ vector of unknowns, and $b$ is a vector of the dependent variables.
 
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$

### Task C)
For each of the following sets of linear equations determine whether a unique solution exits:
\
*Hint:* A matrix is invertible when its determinant is different from zero.

a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$

b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$

c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$

d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$

e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$

f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$


In [39]:
print('a)')
print(np.linalg.solve(np.array([[2, 3], [1, 1]]), np.array([-1, 0])))
print('b)')
print(np.linalg.solve(np.array([[1, 0], [0, 1]]), np.array([5, 7])))
print('c)')
print(np.linalg.solve(np.array([[0, 1], [-2, -3]]), np.array([-1, 2])))
print('d)')
print(np.linalg.solve(np.array([[1, -3, 3], [1, -5, 3], [4, -6, 6]]), np.array([0.5, 0.5, 1])))
print('e)')
print(np.linalg.solve(np.array([[2, 3, 4], [1, 1, 4], [2, 5, 4]]), np.array([2, -2, 3])))



a)
[ 1. -1.]
b)
[5. 7.]
c)
[ 0.5 -1. ]
d)
[ 7.93016446e-18 -3.96508223e-18  1.66666667e-01]
e)
[ 3.     0.5   -1.375]
