# Linear Algebra 
In this tutorial, we will cover some basic terms in linear algebra and go through examples using NumPy. You might got familiar with some these materials in exercise week 2. The tutorial covers the following topics:

1. Data structures in linear algebra 
2. Vectors operations (addition , inner product, length vs number of elements ...)
3. Matrix operations 
4. Special matrices
5. Determinant and inverse of a matrix


## Data structures in linear algbera 
There are different types of objects (or structures) in linear algebra:

- Scalar: Single number
- Vector: Array of numbers
- Matrix: 2-dimensional array of numbers
- Tensor: N-dimensional array of numbers where n > 2


Let’s create an example for each of these objects. 
We will skip “scalar” since it is just a number.
let's first import numpy.


In [5]:
import numpy as np 


A vector that has 4 elements:


In [6]:
v= np.array([1,2,3,4])
print(v)


[1 2 3 4]


A 2x4 matrix:


In [7]:
A= np.array([[1,2,3,4],[5,6,7,8]])
print(A)



[[1 2 3 4]
 [5 6 7 8]]


In [8]:
#print the size of the matrix
print(A.shape)


(2, 4)


A 2x2x4 tensor:


In [9]:
T=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(T)


[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [10]:
#print the size of the tensor
print(T.shape)


(2, 2, 4)


In terms of numpy representations, vector is 1-D array, matrix is 2-D array, and tensor is n-D array (n>2):



<img src="https://miro.medium.com/max/617/0*Vh-pKXTJsdL-9FT0.png" alt="alt text" title="image Title" />


## Vector Operations
- When a vector is multiplied by a scalar, each element of the vector is multiplied with the scalar:


In [11]:
v1=np.array([1,2,3,4])
v1*2


array([2, 4, 6, 8])

- Another common operation is **dot product**. The dot product of two vectors is the sum of the products of elements with regards to position. The first element of one vector is multiplied by the first element of the second vector and so on. The sum of these products is the dot product which can be done with **np.dot()** function.


In [12]:
v1=np.array([1,2,3])
v2=np.array([2,3,4])

np.dot(v1,v2)


20

- Element-wise summation and subtraction on vectors are done with standard math operations.


In [13]:
v1=np.array([1,2,3])
v2=np.array([2,3,4])

print("v1 + v2 is : \n",v1+v2)
print("v1 - v2 is :  \n",v1-v2)


v1 + v2 is : 
 [3 5 7]
v1 - v2 is :  
 [-1 -1 -1]


## Length and dimensionality of vectors
The length of a vector is most commonly measured by the "square root of the sum of the squares of the elements";Euclidean length of a vector. We will calcualte Euclidean length of vector by getting a square root of inner product of it with itself. 



In [14]:
# inner product of v1 with itself
v1_v1_inner_product=v1.dot(v1)
Euc_len_v1=np.sqrt(v1_v1_inner_product)
print('Euclidean length of v1:', Euc_len_v1)


Euclidean length of v1: 3.7416573867739413


We can also calculte Euclidean length by using *np.linalg.norm()*


In [15]:
print('Euclidean length of v1:', np.linalg.norm(v1))


Euclidean length of v1: 3.7416573867739413


### Orthogonal and normal vectors 
We say that 2 vectors are orthogonal if they are perpendicular to each other( i.e. the dot product of the two vectors is zero). 


$ x^Ty=0$



In [38]:
# Orthognonal vectors
v1 = np.array([1, -2, 4])
v2 = np.array([2, 5, 2])

print(v1.dot(v2))


0


If two orthogonal vectors have unit magnitude we call them **orthonromal**. In the code below we normolaize vectors v1 and v2 by dividing bt their Euclidean length. 


In [43]:
v1_normalized= v1/np.linalg.norm(v1)
print('v1_normalized:', v1_normalized)
v2_normalized= v2/np.linalg.norm(v2)
print('v2_normalized:', v2_normalized)

#inner product of orthonormal vectors
print('inner product of v1_normalized and v2_normalized: \n',v1_normalized.dot(v2_normalized))


v1_normalized: [ 0.21821789 -0.43643578  0.87287156]
v2_normalized: [0.34815531 0.87038828 0.34815531]
inner product of v1_normalized and v2_normalized: 
 0.0


## Matrix Operations

Matrix operations are widely-used operation in linear algebra. When solving a system of linear equations, matrix multiplication comes in very handy. let's first have an introduction on properties of matrices and introduce some well-known matrices. 
A matrix is a 2-dimensional array. If the number of elements (size) in both dimensions are the same, then we have a **square matrix**.


In [16]:
A=np.random.randint(5,size=(3,3))
A


array([[2, 2, 3],
       [1, 4, 1],
       [1, 3, 2]])

**Identity matrix** is a square matrix that contains ones on the main diagonal and zeros in all other positions.


In [17]:
I3=np.identity(3, dtype=int)
I3


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [18]:
I4=np.identity(3, dtype=int)
I4


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**Diagonal matrix:** we will use the diag() function. This function is particularly interesting, because if we pass a 1-D array into it, it will return a 2-D array (or a matrix) with the vector values on its 𝑘-th diagonal (𝑘=0 for the main diagonal).

Now let’s create some 1-D array (or a vector):


In [19]:
v = [3, 2, 5]


and create a matrix with 𝑣 on the main diagonal:


In [20]:
D = np.diag(v)
print(D)


[[3 0 0]
 [0 2 0]
 [0 0 5]]


# Matrix multiplication 
Matrix multiplication of two matrices is based on dot products of rows of one matrix with the columns of other matrix. Each element of the product matrix is a dot product of a row in first matrix and a column in the second matrix. Consider matrices A1 and A2 below. The first row of A1 is [1,3,0] and the first column of A2 is [2,0,2]. Dot product of these two vectors is (1x2)+(3x0)+(0x2)=2 which is the element of the product matrix at position [0,0]. The dot product of second row of A1 and second column of A2 gives us the element at position [2,2] which is 36. 


In [21]:
A1=np.array([[1,3,0],[4,4,4]])
A1


array([[1, 3, 0],
       [4, 4, 4]])

In [22]:
A2=np.array([[2,2],[0,4],[2,3]])
A2


array([[2, 2],
       [0, 4],
       [2, 3]])

In [23]:
#A1 first row, A2 first column : position [1,1]
np.dot(A1[0,:],A2[:,0])


2

In [24]:
#A1 second row, A2 first column : position [2,1]
np.dot(A1[1,:],A2[:,0])


16

In [25]:
#A1 first row, A2 second column : position [1,2]
np.dot(A1[0,:],A2[:,1])


14

In [26]:
#A1 second row, A2 second column : position [2,2]
np.dot(A1[1,:],A2[:,1])


36

In [27]:
# A3=A1*A2
A3=np.matmul(A1,A2)
A3


array([[ 2, 14],
       [16, 36]])

One important feature of the identity matrix is that it does not change a matrix when multiplied. So, AI = A. Let’s confirm with numpy:


In [28]:
A=np.random.randint(5,size=(3,3))
A


array([[3, 0, 2],
       [2, 4, 2],
       [2, 1, 3]])

In [29]:
I=np.identity(3, dtype=int)
I


array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [30]:
np.dot(A,I)


array([[3, 0, 2],
       [2, 4, 2],
       [2, 1, 3]])

## Determinant and inverse of a matrix
We use **np.linalg.det()** to get determinant of a matrix. 


In [31]:
A4= np.array([[1,1,1],[0,2,5],[2,5,-1]])
A4


array([[ 1,  1,  1],
       [ 0,  2,  5],
       [ 2,  5, -1]])

In [32]:
np.linalg.det(A4)


-21.0


We use **np.linalg.inv()** function to calculate the inverse of a matrix. We already know that the inverse of a matrix exists if and only if the deteminat of it iz ono-zero. 


In [33]:
A4_inv=np.linalg.inv(A4)
A4_inv


array([[ 1.28571429, -0.28571429, -0.14285714],
       [-0.47619048,  0.14285714,  0.23809524],
       [ 0.19047619,  0.14285714, -0.0952381 ]])

The inverse of a matrix is such that if it is multiplied by the original matrix, it results in identity matrix.


In [34]:
np.dot(A4,A4_inv)


array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  5.55111512e-17,  1.00000000e+00]])

### Diagonal matrix (determinent and inversion)
A diagonal matrix is a square matrix in which all the elements outside the main diagonal are zero (0). The entries on the main diagonal may or may not be null. 


In [45]:
A5=np.diag([5,2,3])
A5


array([[5, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

The determinant of a diagonal matrix is the product of elements of its diagonal. 


In [46]:
np.linalg.det(A5)


29.99999999999999

The inverse of a diagonal matrix is given by replacing the main diagonal elements of the matrix with their reciprocals.


In [47]:
np.linalg.inv(A5)


array([[0.2       , 0.        , 0.        ],
       [0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.33333333]])