# Linear Algebra 
This tutorial will cover basic terms in linear algebra and their implementation in `NumPy`. 
The tutorial includes the following:

1. Data structures in linear algebra 
2. Vectors operations (addition , inner product, length vs number of elements ...)
3. Matrix operations 
4. Special matrices
5. Determinant and inverse of a matrix


## Data structures in linear algebra 
Define:
- Scalar: Single number
- Vector: Array of numbers
- Matrix: 2-dimensional array of numbers
- Tensor: N-dimensional array of numbers where $N$ > 2

`NumPy` represents a vector as a 1-D array, a matrix as a 2-D array (array of arrays), and a $N$-tensor as a $N$-D array (e.g. A 3D-tensor is an array of 2D arrays etc.):

<img src="https://miro.medium.com/max/617/0*Vh-pKXTJsdL-9FT0.png" alt="alt text" title="image Title" />


Creation of the structures in `NumPy` is shown below. (We leave out the scalar case, as it should be trivial)


In [1]:
#import the numpy lib
import numpy as np


In [3]:
#Vector with 4 elements:
v= np.array([1,6,3,1])
print(v)


[1 6 3 1]


In [4]:
# A 2x4 matrix:
A= np.array([[1,42,6,4],[2,6,87,2]])
print(A)



[[ 1 42  6  4]
 [ 2  6 87  2]]


In [8]:
#print the size of the matrix
print(A.shape)


(2, 4)


In [5]:
# A 2x2x4 tensor:
T=np.array([[[1,23,3,4],[42,6,7,87]],[[9,3,11,2],[2,22,15,101]]])
print(T)


[[[  1  23   3   4]
  [ 42   6   7  87]]

 [[  9   3  11   2]
  [  2  22  15 101]]]


In [6]:
#print the size of the tensor
print(T.shape)


(2, 2, 4)


## Vector Operations
- **A vector multiplied by a scalar:** 


In [8]:
v1=np.array([3,22,3,21])
v1*2


array([ 6, 44,  6, 42])

- **dot product/ inner product:** The dot product (see lecture slides for details) of two vectors $a,b$ with $N$ elements each: $$ a\cdot b =\sum_i^N a_ib_i = a^\top b $$
The **dot product** can be calculated using the numpy function `np.dot(a,b)` 


In [2]:
#Create 2 vectors v1 and v2
v1=np.array([1,2,3,42])
v2=np.array([2,3,4,5])
# calculate the dot product
np.dot(v1,v2)


230

- **Summation and Subtraction of 2 vectors:**  Elementwise summation/subtraction (Note this is identical for matrices/tensors)


In [3]:
#create 2 vectors
v1=np.array([1,2,3,42])
v2=np.array([2,3,4,5])

print("v1 + v2 is : \n",v1+v2)
print("v1 - v2 is :  \n",v1-v2)


v1 + v2 is : 
 [ 3  5  7 47]
v1 - v2 is :  
 [-1 -1 -1 37]


## Length and dimensionality of vectors
The Euclidean distance ($L2$-norm) of a vector $a$ is the square root of the inner product $$ |a| =\sqrt{\sum_i^N a_i^2 }= \sqrt{a^\top a}$$.



In [4]:
# inner product of v1 with itself
v1_v1_inner_product=np.dot(v1,v1)
Euc_len_v1=np.sqrt(v1_v1_inner_product)
print('Euclidean distance of v1:', Euc_len_v1)


Euclidean distance of v1: 42.16633728461603


The Euclidean length can also be determined by a single built-in numpy function `np.linalg.norm()`


In [5]:
print('Euclidean distance of v1:', np.linalg.norm(v1))


Euclidean distance of v1: 42.16633728461603


### Orthogonal and normal vectors 
2 vectors are considered orthogonal/perpendicular if their inner product is zero. $$ x^\top y=0$$


In [11]:
# Orthognonal vectors
v1 = np.array([1, -2, 4])
v2 = np.array([2, 5, 2])

print(v1.dot(v2)) ## Alternative way to do dot product. Equivalent to (np.dot(v1,v2))


0


**orthonormal vectors:** Defined as two orthogonal vectors both with unit length.

In the cell below, orthogonal vectors v1 and v2 are normalized by division with their length. 


In [43]:
v1_normalized= v1/np.linalg.norm(v1)
print('v1_normalized:', v1_normalized)
v2_normalized= v2/np.linalg.norm(v2)
print('v2_normalized:', v2_normalized)

#inner product of orthonormal vectors
print('inner product of v1_normalized and v2_normalized: \n',v1_normalized.dot(v2_normalized))


v1_normalized: [ 0.21821789 -0.43643578  0.87287156]
v2_normalized: [0.34815531 0.87038828 0.34815531]
inner product of v1_normalized and v2_normalized: 
 0.0


## Matrix Operations
In the next section is an overview of important matrix properties and well-known matrix compositions. 

**square matrix:** A two dimensional array with the same number of rows and columns.


In [16]:
A=np.random.randint(5,size=(3,3))
A


array([[2, 2, 3],
       [1, 4, 1],
       [1, 3, 2]])

**Identity matrix** is a square matrix that contains ones on the diagonal and zeros elsewhere.
 
The NumPy function `np.identity(N)` creates an identity matrix with N elements on the diagonal. 


In [6]:
I3=np.identity(3)
I3


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
I4=np.identity(4)
I4


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Diagonal matrix:** Only have non-zero elements on the diagonal.

The NumPy function `np.diag(a)` creates a 2D array (diagonal matrix)
 given a 1D array (list/vector containing diagonal elements) as input. 


In [11]:
# Create an array:
v = np.array([3., 2., 5.])


In [12]:
# Create a matrix with elements of v on the diagonal:
D = np.diag(v)
print(D)


[[3. 0. 0.]
 [0. 2. 0.]
 [0. 0. 5.]]


# Matrix multiplication 
**Matrix multiplication of two matrices consist of inner products of row-column pairs:**

Consider the matrices A1 and A2:

The first row of A1 is [1,3,0] and the first column of A2 is [2,0,2]. The inner product of the first row of A1 and the column of A2 ($(1\times 2)+(3\times 0)+(0\times 2)=2$) gives the element of the product matrix at index $(1,1)$ but $[0,0]$ in the NumPy array.

Similarly, the inner product of second row of A1 and second column of A2 is $36$ which is the value of the product matrix at index $[1,1]$ in the NumPy array. 


In [15]:
# Create a 2x3 matrix A1
A1=np.array([[1,3,0],[4,4,4]])
A1


array([[1, 3, 0],
       [4, 4, 4]])

In [14]:
# Create a 3x2 matrix A2
A2=np.array([[2,2],[0,4],[2,3]])
A2


array([[2, 2],
       [0, 4],
       [2, 3]])

In [23]:
#A1 first row, A2 first column : position [1,1]
np.dot(A1[0,:],A2[:,0])


2

In [24]:
#A1 second row, A2 first column : position [2,1]
np.dot(A1[1,:],A2[:,0])


16

In [25]:
#A1 first row, A2 second column : position [1,2]
np.dot(A1[0,:],A2[:,1])


14

In [26]:
#A1 second row, A2 second column : position [2,2]
np.dot(A1[1,:],A2[:,1])


36

In [16]:
# A1*A2
np.matmul(A1,A2)


array([[ 2, 14],
       [16, 36]])

Multiplying a matrix A (from either left or right) with the identity matrix yields the matrix A. Thus, 
$$AI = A = IA.$$
An example is provided below:


In [17]:
# create 3x3 matrix A with random values between 0 and 4.
A=np.random.randint(5,size=(3,3))
A


array([[2, 4, 3],
       [4, 3, 2],
       [2, 4, 0]])

In [18]:
# create 3x3 identity matrix.
I=np.identity(3)
I


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.dot(A,I)


array([[2., 4., 3.],
       [4., 3., 2.],
       [2., 4., 0.]])

## Determinant and inverse of a matrix
We use **np.linalg.det()** to get determinant of a matrix. 


In [22]:
# create 3x3 array
A4= np.array([[1,1,1],[0,2,5],[2,5,-1]])
A4


array([[ 1,  1,  1],
       [ 0,  2,  5],
       [ 2,  5, -1]])

In [23]:
# calculate the determinant 
np.linalg.det(A4)


-21.0


The function `np.linalg.inv(A)` can be used to calculate the inverse of a matrix `A`. 

**Note:** The function returns an error when the matrix is singular (i.e. the determinant is zero)
Hence it would be wise to write:


In [36]:
if np.linalg.det(A4)!=0:
    A4_inv=np.linalg.inv(A4)
    print(A4_inv)
else: 
    print('The matrix is singular, hence its inverse does not exists')


[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]


The matrix A multiplied by its inverse yields the identity matrix.


In [37]:
np.dot(A4,A4_inv)


array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-1.11022302e-16,  5.55111512e-17,  1.00000000e+00]])

### Diagonal matrice (determinant and inversion)


In [45]:
# Create a diagonal matrix 
A5=np.diag([5,2,3])
A5


array([[5, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

The determinant of a diagonal matrix is the product of the elements on the diagonal. 


In [46]:
np.linalg.det(A5)


29.99999999999999

The inverse of a diagonal matrix is the reciprocal of each element on the diagonal.


In [47]:
np.linalg.inv(A5)


array([[0.2       , 0.        , 0.        ],
       [0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.33333333]])

This concludes the toturial.
